AccountibiliBuddy/Models/Goal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountibiliBuddy.Models
{
    public class Goal
    {
        [Key]
        public int GoalId { get; set; }

        [Required]
        [StringLength(55)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }


        public bool CompletionStatus { get; set; }

        [Required]  
        
        [RegularExpression("([1-9][0-9]*)",
         ErrorMessage = "Please Choose A Goal Type")]

        public int GoalTypeId { get; set; }

        public GoalType GoalType { get; set; }

        [Required]
        public string UserId { get; set; }

        [Required]
        public ApplicationUser User { get; set; }



    }
}

AccountibiliBuddy/Models/GoalType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountibiliBuddy.Models
{
    public class GoalType
    {
        [Key]
        public int GoalTypeId { get; set; }
        [Required]
        public string Type { get; set; }

        public int PointValue { get; set; }
    }
}

AccountibiliBuddy/Models/GoalViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountibiliBuddy.Models
{
    public class GoalViewModel
    {
        public Goal Goal { get; set; }

        public List<SelectListItem> GoalTypes { get; set; } = new List<SelectListItem>();
    }
}

AccountibiliBuddy/Models/ViewModels/GoalViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountibiliBuddy.Models.ViewModels
{
    public class GoalViewModel
    {
        public Goal Goal { get; set; }

        public List<SelectListItem> GoalTypes { get; set; } = new List<SelectListItem>();
    }
}

AccountibiliBuddy/Controllers/GoalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AccountibiliBuddy.Data;
using AccountibiliBuddy.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AccountibiliBuddy.Models.ViewModels;

namespace AccountibiliBuddy.Controllers
{
    public class GoalsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public GoalsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }
        [Authorize]
        // GET: Goals
        public async Task<IActionResult> Index()
        {
            ProgressViewModel ViewModel = new ProgressViewModel();

            var applicationDbContext = _context.Goal.Include(p => p.User);

            var user = await GetCurrentUserAsync();

            var userCheck = await _context.Goal.Where(g => g.UserId == user.Id && g.Date.Date == DateTime.Now.Date && g.Date.Month == DateTime.Now.Month && g.Date.Day == DateTime.Now.Day ).ToListAsync();

            if (userCheck.Count() < 1)
            {
                //redirect to a page that tells them 
                //and gives them an option to create a payment type
                return View("NoGoals");
            }


            var AllGoals = _context.Goal.Include(p => p.User).ToList();

            var Currentuser = await GetCurrentUserAsync();

            var GoalsForCurrentDay = await _context.Goal.Where(g => g.UserId == Currentuser.Id && g.Date.Date == DateTime.Now.Date && g.Date.Month == DateTime.Now.Month && g.Date.Day == DateTime.Now.Day).ToListAsync();

            double TotalNumberOfGoals = GoalsForCurrentDay.Count();

            double NumberOfCompletedGoals = GoalsForCurrentDay.Where(g => g.CompletionStatus == true).Count();

            double CounterforProgressBar = (NumberOfCompletedGoals / TotalNumberOfGoals) * 100;

            ViewModel.Goals = userCheck;

            ViewModel.DailyProgressCounter = CounterforProgressBar;
            ViewModel.DailyProgressPercent = $"{Math.Round(CounterforProgressBar)}%";

            return View(ViewModel);
        }



        [Authorize]
        // GET: Goals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goal = await _context.Goal.FindAsync(id);
            if (goal == null)
            {
                return NotFound();
            }
            GoalViewModel ViewModel = new GoalViewModel();

            ViewModel.Goal = await _context.Goal
            .FirstOrDefaultAsync(m => m.GoalId == id);

            ViewModel.GoalTypes = _context.GoalType.Select(gt => new SelectListItem

            {
                Text = gt.Type,
                Value = gt.GoalTypeId.ToString()
            }
    ).ToList();

            return View(ViewModel);
        }
        [Authorize]
        // GET: Goals/Create
        public IActionResult Create()
        {
            //instance  of view model
            GoalViewModel ViewModel = new GoalViewModel();

            //accessing the view 
            ViewModel.GoalTypes = _context.GoalType.Select(gt => new SelectListItem

            {
                Text = gt.Type,
                Value = gt.GoalTypeId.ToString()
            }
        ).ToList();

            ViewModel.GoalTypes.Insert(0, new SelectListItem() { Value = "-1", Text = "Choose A Goal Type" });

            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View(ViewModel);
        }

           
        
        // POST: Goals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( GoalViewModel viewModel)
        {
            //removes the user and userid so the model state doesnt think that the information is invalid
            ModelState.Remove("Goal.User");
            ModelState.Remove("Goal.UserId");
            if (ModelState.IsValid )
            {
                //gets the current user
                var user = await GetCurrentUserAsync();
                //grabs the current user's id
                viewModel.Goal.UserId = user.Id;
                //sets the completion status to false
                viewModel.Goal.CompletionStatus = false;
                _context.Add(viewModel.Goal);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
       
            return View(viewModel);
        }
        [Authorize]
        // GET: Goals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goal = await _context.Goal.FindAsync(id);
            if (goal == null)
            {
                return NotFound();
            }
            GoalViewModel ViewModel = new GoalViewModel();

            ViewModel.Goal = await _context.Goal
            .FirstOrDefaultAsync(m => m.GoalId == id);
            


            ViewModel.GoalTypes = _context.GoalType.Select(gt => new SelectListItem

            {
                Text = gt.Type,
                Value = gt.GoalTypeId.ToString()
            }
    ).ToList();

            return View(ViewModel);
        }

        // POST: Goals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  GoalViewModel viewModel)
        {
            if (id != viewModel.Goal.GoalId)
            {
                return NotFound();
            }

            ModelState.Remove("Goal.User");
            ModelState.Remove("Goal.UserId");
            
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await GetCurrentUserAsync();
                    //grabs the current user's id
                    viewModel.Goal.UserId = user.Id;
                    viewModel.Goal.CompletionStatus = viewModel.Goal.CompletionStatus;



                    _context.Update(viewModel.Goal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GoalExists(viewModel.Goal.GoalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GoalTypeId"] = new SelectList(_context.GoalType, "Id", "Id", viewModel.Goal.GoalTypeId);
            return View(viewModel);
        }


        // GET: Goals/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goal = await _context.Goal
                .FirstOrDefaultAsync(m => m.GoalId == id);
            if (goal == null)
            {
                return NotFound();
            }

            return View(goal);
        }

        // POST: Goals/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var goal = await _context.Goal.FindAsync(id);
            _context.Goal.Remove(goal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GoalExists(int id)
        {
            return _context.Goal.Any(e => e.GoalId == id);
        }

       
        public async Task<IActionResult> Complete(int id, Goal goal)
        {
            var Complete = await _context.Goal.FindAsync(id);
            Complete.CompletionStatus = true;
            _context.Update(Complete);
            await _context.SaveChangesAsync();

            return Ok(Complete);

        }



        public async Task<IActionResult> ChooseDate(DateTime DateSearch)
        {
            ProgressViewModel ViewModel = new ProgressViewModel();

            ViewData["UserDateInput"] = DateSearch;

            var applicationDbContext = _context.Goal.Include(p => p.User);

            var user = await GetCurrentUserAsync();

            var searchDate = applicationDbContext.Where(g => g.UserId == user.Id && g.Date.Day == DateSearch.Day && g.Date.Month == DateSearch.Month && g.Date.Year == DateSearch.Year ).ToList();

            double TotalNumberOfGoals = searchDate.Count();

            double NumberOfCompletedGoals = searchDate.Where(g => g.CompletionStatus == true).Count();

            double CounterforProgressBar = (NumberOfCompletedGoals / TotalNumberOfGoals) * 100;

            ViewModel.Goals = searchDate;

            ViewModel.DailyProgressCounter = CounterforProgressBar;
            ViewModel.DailyProgressPercent = $"{Math.Round(CounterforProgressBar)}%";
            ViewModel.Date = DateSearch;

            return View(ViewModel);

        }

AccountibiliBuddy/Views/Goals/ChooseDate.cshtml
@model AccountibiliBuddy.Models.ViewModels.ProgressViewModel


@{
    ViewData["ChooseDate"] = "ChooseDate";
}

<h1>Choose A Date</h1>

<div class="form-group">
    <form asp-action="ChooseDate">
        <input type="date" name="DateSearch" value="@ViewData["UserDateInput"]" class="form-control" />
        <br />
        <input type="submit" value="Search" class="btn btn-info" asp-controller="Goals" asp-action="ChooseDate" />
    </form>
</div>

@if (Model.Goals.Count() < 1 && Model.Date == new DateTime(1, 1, 0001))
{

}
else if (Model.Goals.Count() < 1)
{
    <h1>No Goals For This Date</h1>
    <p>
        <a asp-action="Create">Create Some Goals</a>
    </p>
}
else if (Model.Goals.Count() >= 1)
{


    <div class="card-group">

        <div class="card-columns">

            @foreach (AccountibiliBuddy.Models.Goal item in Model.Goals)
            {
                @if (item.Date.Date < DateTime.Now.Date)
                {
                    <div class="card border-info mb-3" style="max-width: 18rem;">
                        <div class="card-title border-info">
                            <div class="card-header border-info">@item.Date.Month/@item.Date.Day/@item.Date.Year</div>
                            <div class="card-body text-dark">
                                <h5 class="card-title">@item.Name</h5>

                                @if (item.CompletionStatus == true)
                                {
                                    <ul>
                                        <li>Completed</li>
                                    </ul>
                                }
                                else if (item.CompletionStatus == false)
                                {
                                    <ul>
                                        <li>Not Completed</li>
                                    </ul>
                                }



                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="card border-info mb-3" style="max-width: 18rem;">
                        <div class="card-title border-info">
                            <div class="card-header border-info">@item.Date.Month/@item.Date.Day/@item.Date.Year</div>
                            <div class="card-body text-dark">
                                <h5 class="card-title">@item.Name</h5>
                                @if (item.CompletionStatus == false)
                                {
                                    <div id="complete">
                                        <button id="@item.GoalId" class="btn btn-primary">Complete?</button>
                                    </div>
                                }
                                else
                                {
                                    <div>
                                        @Html.DisplayFor(modelItem => item.CompletionStatus)
                                    </div>
                                }
                                <a asp-action="Edit" asp-route-id="@item.GoalId">Edit</a> |
                                <a asp-action="Delete" asp-route-id="@item.GoalId">Delete</a>
                            </div>
                        </div>
                    </div>
                }

            }
        </div>
                </div>

    <h6>Progress</h6>

    @if (Model.DailyProgressCounter == 100)
    {
        <div class="progress">
            <div class="progress-bar  bg-success  " role="progressbar"
                 aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                @Model.DailyProgressPercent
            </div>
        </div>
    }
    else if (Model.DailyProgressCounter <=99.9 && Model.DailyProgressCounter >=90)
    {
        <div class="progress">
            <div class="progress-bar  bg-success progress-bar-striped progress-bar-animated " role="progressbar"
                 aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                @Model.DailyProgressPercent
            </div>
        </div>
    }
    else if (Model.DailyProgressCounter <= 89.9 && Model.DailyProgressCounter >= 80)
    {
        <div class="progress">
            <div class="progress-bar  bg-info progress-bar-striped progress-bar-animated" role="progressbar"
                 aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                @Model.DailyProgressPercent
            </div>
        </div>
    }
    else if (Model.DailyProgressCounter <= 79.9 && Model.DailyProgressCounter >= 60)
    {
        <div class="progress">
            <div class="progress-bar  bg-warning progress-bar-striped progress-bar-animated" role="progressbar"
                 aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                @Model.DailyProgressPercent
            </div>
        </div>
    }
    else if (Model.DailyProgressCounter <= 59.9 && Model.DailyProgressCounter >= 0)
    {
        <div class="progress">
            <div class="progress-bar  bg-danger progress-bar-striped progress-bar-animated" role="progressbar"
                 aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                @Model.DailyProgressPercent
            </div>
        </div>
    }
}

AccountibiliBuddy/Views/Goals/Create.cshtml
@model AccountibiliBuddy.Models.ViewModels.GoalViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Goal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Goal.Name" class="control-label"></label>
                <input asp-for="Goal.Name" class="form-control" />
                <span asp-validation-for="Goal.Name" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Goal.Date" class="control-label"></label>
                <input asp-for="Goal.Date" class="form-control"  />
                <span asp-validation-for="Goal.Date" class="text-danger"></span>
            </div>
            <div class="form-group"> 
                <label  class="control-label"></label>
                <select asp-for="Goal.GoalTypeId" asp-items="@Model.GoalTypes" > </select>
                <span asp-validation-for="Goal.GoalTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AccountibiliBuddy/Views/Goals/Delete.cshtml
@model AccountibiliBuddy.Models.Goal

@{
    ViewData["Title"] = "Delete";
}



<h3>Are you sure you want to delete this?</h3>


<div class="card border-dark mb-3" style="max-width: 18rem;">
    <div class="card-header">@Html.DisplayFor(model => model.Date)</div>
    <div class="card-body text-dark">
        <h5 class="card-title">@Html.DisplayFor(model => model.Name)</h5>

        <form asp-action="Delete">
            <input type="hidden" asp-for="GoalId" />
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            
        </form>
    </div>
</div>
<a asp-action="Index">Back to List</a>

AccountibiliBuddy/Views/Goals/Details.cshtml
@model AccountibiliBuddy.Models.Goal

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Goal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompletionStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompletionStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GoalId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AccountibiliBuddy/Views/Goals/Edit.cshtml
@model AccountibiliBuddy.Models.ViewModels.GoalViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Goal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Goal.GoalId" />
            <div class="form-group">
                <label asp-for="Goal.Name" class="control-label"></label>
                <input asp-for="Goal.Name" class="form-control" />
                <span asp-validation-for="Goal.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Goal.Date" class="control-label"></label>
                <input asp-for="Goal.Date" class="form-control" />
                <span asp-validation-for="Goal.Date" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label class="control-label"></label>
                <select asp-for="Goal.GoalTypeId" asp-items="@Model.GoalTypes"></select>
                <span asp-validation-for="Goal.GoalTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AccountibiliBuddy/Views/Goals/Index.cshtml
@model AccountibiliBuddy.Models.ViewModels.ProgressViewModel

@{
    ViewData["Title"] = "Index";
}

    <div>

        <h1>Goals For Today</h1>

        <p>
            <a asp-action="Create">Create New</a>
        </p>

        <div class="card-group">
            
                <div class="card-columns">

                    @foreach (AccountibiliBuddy.Models.Goal item in Model.Goals)
                    {





                    <div class="card border-info mb-3" style="max-width: 18rem;">
                        <div class="card-title border-info">
                            <div class="card-header border-info">@item.Date.Month/@item.Date.Day/@item.Date.Year</div>
                            <div class="card-body text-dark">
                                <h5 class="card-title ">@item.Name</h5>
                                @if (item.CompletionStatus == false)
                                {
                                    <div id="complete">
                                        <button id="@item.GoalId" class="btn btn-info">Complete?</button>
                                    </div>
                                }
                                else
                                {
                                    <div>
                                        @Html.DisplayFor(modelItem => item.CompletionStatus)
                                    </div>
                                }
                                <br />
                                @if (item.CompletionStatus == false)
                                {
                                    <a asp-action="Edit" asp-route-id="@item.GoalId">Edit</a> 
                                    <a asp-action="Delete" asp-route-id ="@item.GoalId"> Delete </a>
                                }
                                else if (item.CompletionStatus == true)
                                {

                                }


                            </div>
                        </div>
                    </div>







                            }
                        </div>
                    </div>
        



            <h6>Progress</h6>

            @if (Model.DailyProgressCounter == 100)
            {
                <div class="progress">
                    <div class="progress-bar  bg-success  " role="progressbar"
                         aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                        @Model.DailyProgressPercent
                    </div>
                </div>
            }
            else if (Model.DailyProgressCounter <=99.9 && Model.DailyProgressCounter >=90)
            {
                <div class="progress">
                    <div class="progress-bar  bg-success progress-bar-striped progress-bar-animated " role="progressbar"
                         aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                        @Model.DailyProgressPercent
                    </div>
                </div>
            }
            else if (Model.DailyProgressCounter <=89.9 && Model.DailyProgressCounter >= 80)
            {
                <div class="progress">
                    <div class="progress-bar  bg-info progress-bar-striped progress-bar-animated" role="progressbar"
                         aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                        @Model.DailyProgressPercent
                    </div>
                </div>
            }
            else if (Model.DailyProgressCounter <= 79.9 && Model.DailyProgressCounter >= 60)
            {
                <div class="progress">
                    <div class="progress-bar  bg-warning progress-bar-striped progress-bar-animated" role="progressbar"
                         aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                        @Model.DailyProgressPercent
                    </div>
                </div>
            }
            else if(Model.DailyProgressCounter <= 59.9 && Model.DailyProgressCounter >= 0)
            {
                <div class="progress">
                    <div class="progress-bar  bg-danger progress-bar-striped progress-bar-animated" role="progressbar"
                         aria-valuenow="@Model.DailyProgressCounter" aria-valuemin="0" aria-valuemax="100" style="width: @Model.DailyProgressPercent ">
                        @Model.DailyProgressPercent
                    </div>
                </div>
            }

AccountibiliBuddy/Views/Goals/NoGoals.cshtml
@{
    ViewData["NoGoals"] = "NoGoals";
}

<h1>You Haven't Set Any Goals For Today</h1>

<a class="nav-link" asp-area="" asp-controller="Goals" asp-action="Create">Create Some Goals?</a>